/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './module';
import * as i2 from '@angular/http';
export const TrumbowygEditorModuleNgFactory:i0.NgModuleFactory<i1.TrumbowygEditorModule> = i0.ɵcmf(i1.TrumbowygEditorModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.BrowserXhr,i2.BrowserXhr,([] as any[])),i0.ɵmpd(4608,i2.ResponseOptions,
          i2.BaseResponseOptions,([] as any[])),i0.ɵmpd(5120,i2.XSRFStrategy,i2.ɵb,
          ([] as any[])),i0.ɵmpd(4608,i2.XHRBackend,i2.XHRBackend,[i2.BrowserXhr,i2.ResponseOptions,
          i2.XSRFStrategy]),i0.ɵmpd(4608,i2.RequestOptions,i2.BaseRequestOptions,([] as any[])),
          i0.ɵmpd(5120,i2.Http,i2.ɵc,[i2.XHRBackend,i2.RequestOptions]),i0.ɵmpd(512,
              i2.HttpModule,i2.HttpModule,([] as any[])),i0.ɵmpd(512,i1.TrumbowygEditorModule,
              i1.TrumbowygEditorModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvc2FuL1dvcmsvY29sbGFib3JhdG9yL25nMi10cnVtYm93eWcvc3JjL21vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL3Nhbi9Xb3JrL2NvbGxhYm9yYXRvci9uZzItdHJ1bWJvd3lnL3NyYy9tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
