/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './module';
import * as import2 from '@angular/core/src/di/injector';
class TrumbowygEditorModuleInjector extends import0.NgModuleInjector<import1.TrumbowygEditorModule> {
  _TrumbowygEditorModule_0:import1.TrumbowygEditorModule;
  constructor(parent:import2.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.TrumbowygEditorModule {
    this._TrumbowygEditorModule_0 = new import1.TrumbowygEditorModule();
    return this._TrumbowygEditorModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.TrumbowygEditorModule)) { return this._TrumbowygEditorModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const TrumbowygEditorModuleNgFactory:import0.NgModuleFactory<import1.TrumbowygEditorModule> = new import0.NgModuleFactory(TrumbowygEditorModuleInjector,import1.TrumbowygEditorModule);